{

'whitelist_statuses' => [
    'STATUS_ANY_ERROR',
],

'whitelist_patterns' => [
    # 2020-05-15 10.2 dev
    # mysqld: /home/matthias_leich_mariadb_com/Server/enterprise_10.2-MDEV-22456/storage/innobase/btr/btr0sea.cc:2113: ulint btr_search_hash_table_validate(ulint): Assertion `block->page.id.space() == block->index->space' failed.
    [ 'TBR-552'    , 'mysqld: .{1,150}btr0sea.cc:.{1,30} ulint btr_search_hash_table_validate.{1,30}: Assertion .block->page.id.space\(\) == block->index->space. failed.' ],
    # with virt column
    # mysqld: /home/matthias_leich_mariadb_com/Server/enterprise_10.2-MDEV-22456/storage/innobase/btr/btr0sea.cc:1229: void btr_search_drop_page_hash_index(buf_block_t*): Assertion `!btr_search_own_any(RW_LOCK_X)' failed.
    [ 'TBR-551'    , 'mysqld: .{1,150}btr0sea.cc:.{1,30} void btr_search_drop_page_hash_index.{1,100}: Assertion .\!btr_search_own_any\(RW_LOCK_X\). failed.' ],
    # InnoDB: Assertion failure in file /home/matthias_leich_mariadb_com/Server/enterprise_10.2-MDEV-22456/storage/innobase/btr/btr0sea.cc line 1647
    # 2020-05-13T17:22:32 [18314] | InnoDB: Failing assertion: !block->index || block->index == index
    [ 'TBR-550'    , 'InnoDB: Assertion failure in file.{1,200}btr0sea.cc line.{1,200}InnoDB: Failing assertion: \!block->index \|\| block->index == index' ],


    # We have no special focus.
    # 2020-04-21 bb-10.5_marko
    # InnoDB: Failing assertion: node->n_pending == 0
    [ 'TBR-400'    , 'InnoDB: Failing assertion: node->n_pending == 0' ],
    # InnoDB: Failing assertion: table->n_rec_locks == 0  (crash during shutdown)
    [ 'TBR-401'    , 'InnoDB: Failing assertion: table->n_rec_locks == 0' ],

    # mysqld: /home/mleich/10.5-kevgs/sql/sql_base.cc:929: void close_thread_table(THD*, TABLE**): Assertion `!table->file->keyread_enabled()' failed.
    [ 'MDEV-22062' , 'mysqld: .{1,150}sql_base.cc:.{1,30} void close_thread_table.{1,150}: Assertion .\!table->file->keyread_enabled\(\). failed.' ],

    # Enterprise 10.5-kevgs 2020-04-22
    # AFAIR I have seen that somewhere else    Its the restart after crash
    # mysqld: /home/mleich/10.5-kevgs/storage/innobase/log/log0recv.cc:271: log_phys_t::apply_status log_phys_t::apply(const buf_block_t&, uint16_t&) const: Assertion `mach_read_from_4(frame + 4U) == block.page.id.page_no()' failed.
    [ 'MENT-601_5' , 'mysqld: .{1,150}log0recv.cc:.{1,30} log_phys_t::apply_status log_phys_t::apply.{1,150}: Assertion .mach_read_from_4\(frame \+ 4U\) == block.page.id.page_no\(\). failed.' ],
    # Crash around shutdown
    # mysqld: /home/mleich/10.5-kevgs/storage/innobase/log/log0log.cc:868: void log_t::file::close_file(): Assertion `future_fd.is_opened()' failed.
    [ 'MENT-601_6' , 'mysqld: .{1,150}log0log.cc:.{1,30} void log_t::file::close_file\(\): Assertion .future_fd.is_opened\(\). failed.' ],
    # mysqld: /home/mleich/10.5-kevgs/sql/sql_parse.cc:7444: void THD::reset_for_next_command(bool): Assertion `binlog_table_maps == 0 || locked_tables_mode == LTM_LOCK_TABLES' failed.
    [ 'TBR-402'    , 'mysqld: .{1,150}sql_parse.cc:.{1,30} void THD::reset_for_next_command\(bool\): Assertion .binlog_table_maps == 0 \|\| locked_tables_mode == LTM_LOCK_TABLES. failed.' ],
    # During restart after crash
    # [ERROR] InnoDB: Missing FILE_CHECKPOINT at 11942673 between the checkpoint 11849133 and the end 11942400.
    [ 'MENT-601_7' , '\[ERROR\] InnoDB: Missing FILE_CHECKPOINT at .{1,30} between the checkpoint .{1,30} and the end .{1,30}.' ],
    # Just a crash
    # mysqld: /home/mleich/10.5-kevgs/storage/innobase/log/log0log.cc:1021: void future_log_write(st_::span<unsigned char>): Assertion `buf.size() <= log_sys.log.future_file_size - (4 * 512U)' failed.
    [ 'MENT-601_8' , 'mysqld: .{1,150}log0log.cc:.{1,30} void future_log_write.{1,150}: Assertion .buf.size\(\) <= log_sys.log.future_file_size - \(4 \* 512U\). failed.' ],
    # crash on restart after server process kill  not kevgs specific
    # 2020-04-22T13:30:33 [77797] 2020-04-22 13:30:32 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=17629936
    # 2020-04-22T13:30:33 [77797] 2020-04-22 13:30:32 0 [Note] InnoDB: Starting final batch to recover 36 pages from redo log.
    # ....
    # 2020-04-22T13:30:33 [77797] mysqld: /home/mleich/10.5-kevgs/storage/innobase/row/row0purge.cc:133: bool row_purge_remove_clust_if_poss_low(purge_node_t*, ulint): Assertion `rec_get_deleted_flag(rec, rec_offs_comp(offsets))' failed.
    [ 'TBR-282'    , 'mysqld: .{1,150}row0purge.cc:.{1,30} bool row_purge_remove_clust_if_poss_low.{1,100}: Assertion .rec_get_deleted_flag\(rec, rec_offs_comp\(offsets\)\). failed.' ],
    # + experimental fix

    # in 10.5
    # assert in crash recovery
    # mysqld: /home/mleich/10.5-kevgs/storage/innobase/include/btr0btr.h:241: buf_block_t* btr_block_get_func(const dict_index_t&, ulint, ulint, bool, const char*, unsigned int, mtr_t*): Assertion `err == DB_SUCCESS' failed.
    [ 'MDEV-22369' , 'mysqld: .{1,150}btr0btr.h:.{1,30} buf_block_t\* btr_block_get_func.{1,200}: Assertion .err == DB_SUCCESS. failed.' ],
    # not seen sice some time but known
    [ 'TBR-3' , 'mysqld: .{1,150}lock0lock.cc.{1,20} my_bool lock_rec_other_trx_holds_expl_callback.{1,150}: Assertion .\!expl_lock \|\| expl_lock->trx == arg->impl_trx. failed.' ],



    # 2020-03-20 10.2 Dev
    # SEGV when fiddling with ALTER and FK
    # 2020-03-19T20:45:04 [6332] #3  <signal handler called>
    # 2020-03-19T20:45:04 [6332] #4  0x000055ad1da0b0db in cmp_cols_are_equal (col1=0x7efe38115660, col2=0xa5a5a5a5a5a5a5a5, check_charsets=1) at /home/mleich/bb-10.2-thiru/storage/innobase/rem/rem0cmp.cc:108
    # 2020-03-19T20:45:04 [6332] #5  0x000055ad1dbd2b07 in dict_foreign_qualify_index (table=0x7efea00c40b0, col_names=0x0, columns=0x7efe780e6168, n_cols=1, index=0x7efe6c227870, types_idx=0x7efea007fca0, check_charsets=true, check_null=8, error=0x0, err_col_no=0x0, err_index=0x0) at /home/mleich/bb-10.2-thiru/storage/innobase/dict/dict0dict.cc:6605
    # 2020-03-19T20:45:04 [6332] #6  0x000055ad1dbc9d83 in dict_foreign_find_index (table=0x7efea00c40b0, col_names=0x0, columns=0x7efe780e6168, n_cols=1, types_idx=0x7efea007fca0, check_charsets=true, check_null=8, error=0x0, err_col_no=0x0, err_index=0x0) at /home/mleich/bb-10.2-thiru/storage/innobase/dict/dict0dict.cc:3091
    # 2020-03-19T20:45:04 [6332] #7  0x000055ad1d959300 in innobase_update_foreign_try (ctx=0x7efe78012c38, trx=0x7eff395a3d30, table_name=0x7efe940cc7fd "BB") at /home/mleich/bb-10.2-thiru/storage/innobase/handler/handler0alter.cc:7338
    # 2020-03-19T20:45:04 [6332] #8  0x000055ad1d95edc7 in commit_try_norebuild (ha_alter_info=0x7eff381cbc50, ctx=0x7efe78012c38, altered_table=0x7efe780a9838, old_table=0x7efe780f0708, trx=0x7eff395a3d30, table_name=0x7efe940cc7fd "BB") at /home/mleich/bb-10.2-thiru/storage/innobase/handler/handler0alter.cc:7729
    # 2020-03-19T20:45:04 [6332] #9  0x000055ad1d95b099 in ha_innobase::commit_inplace_alter_table
    [ 'TBR-291'    , '<signal handler called>.{1,500}in cmp_cols_are_equal .{1,500}in dict_foreign_qualify_index .{1,500}in dict_foreign_find_index .{1,500} innobase_update_foreign_try .{1,500} commit_try_norebuild .{1,500} ha_innobase::commit_inplace_alter_table ' ],


    # Corruption in general seen in many releases etc.
    # 2020-04-22T14:04:18 [79536] Executor::MySQL::execute: Query: INSERT INTO `table500_innodb_dynamic_int` ( `col_varchar_latin1_not_null_key` ) VALUES ( 0 ) ON DUPLICATE KEY UPDATE `col_int_not_null` = NULL /* E_R Thread2 QNO 1989 CON_ID 13 */  failed: 1032 Can't find record in 'table500_innodb_dynamic_int'
    # 2020-04-22T14:04:18 [79536] Thread2 in Mixer : Critical failure STATUS_DATABASE_CORRUPTION (106), Error 1032 reported at dsn dbi:mysql:host=127.0.0.1:port=27100:user=root:database=test:mysql_local_infile=1
    # Error 1032 reported at dsn 
    [ 'TBR-403'    , 'Error 1032 reported at dsn ' ],

    # Known
    # InnoDB: Failing assertion: prebuilt->template_type == ROW_MYSQL_WHOLE_ROW
    [ 'MDEV-21428'    , 'InnoDB: Failing assertion: prebuilt->template_type == ROW_MYSQL_WHOLE_ROW' ],
    [ 'MDEV-nnnnn' , 'mysqld: .{1,150}handler.cc:.{1,30} int handler::ha_reset\(\): Assertion .\!table->file->keyread_enabled\(\). failed.' ],


    # The error pattern is not highly specific. And MDEV-21669 looking like that is fixed.
    [ 'CATCH-0001' , 'indexes inside InnoDB, which is different from the number of indexes' ],
    #  mysqld: /work/bb-10.5-MDEV-12353/storage/innobase/row/row0sel.cc:5163: dberr_t row_search_mvcc(byte*, page_cur_mode_t, row_prebuilt_t*, ulint, ulint): Assertion `index != clust_index || row_get_rec_trx_id(rec, index, offsets)' failed.
    [ 'TBR-53'     , 'mysqld: .{1,150}row0sel.cc:.{1,30} dberr_t row_search_mvcc.{1,150}: Assertion .index \!= clust_index \|\| row_get_rec_trx_id\(rec, index, offsets\). failed.' ],
    # Most frequent in Mariabackup prepare and even on non debug build
    # [00] 2020-03-19 12:00:28 mariabackup: using the following InnoDB configuration for recovery:
    # ...
    # [ERROR] InnoDB: Not applying DELETE_ROW_FORMAT_DYNAMIC due to corruption on [page id: space=7, page number=118]
    # Affects mariabackup ... prepare but also restart invoking recovery
    [ 'MDEV-21899' , '\[ERROR\] InnoDB: Not applying .{1,50} due to corruption on' ],
    # Most frequent in Mariabackup prepare and even on non debug build
    [ 'TBR-281'    , '\[ERROR\] InnoDB: Malformed log record; set innodb_force_recovery=1 to ignore' ],
    # mariabackup: /home/mleich/10.5/storage/innobase/page/page0cur.cc:2068: void page_mem_free(const buf_block_t&, rec_t*, size_t, size_t): Assertion `garbage >= extra_savings' failed.
    [ 'TBR-245'    , 'mariabackup: .{1,150}page0cur.cc:.{1,30} page_mem_free.{1,150}: Assertion .garbage >= extra_savings. failed.' ],
    # mariabackup: /home/mleich/10.5/storage/innobase/log/log0recv.cc:495: log_phys_t::apply_status log_phys_t::apply(const buf_block_t&, uint16_t&) const: Assertion `rlen < llen' failed.
    [ 'TBR-246'    , 'mariabackup: .{1,150}log0recv.cc:.{1,30} log_phys_t::apply_status log_phys_t::apply.{1,150}: Assertion .rlen < llen.' ],
    # FATAL ERROR: 2020-03-06 18:19:43 Failed to not validate first page of the file <80>^[^?÷<86>U, error 42
    [ 'TBR-247'    , 'FATAL ERROR: .{1,150} Failed to not validate first page of the file ' ],
    [ 'TBR-15528_1' , 'mysqld: .{1,150}buf0dblwr.cc:.{1,30} void buf_dblwr_update.{1,300}: Assertion .buf_dblwr->batch_running. failed.' ],
    # This comes even if the tests do not run DDL  XA is most probably required
    [ 'TBR-253'    , 'mysqld: .{1,150}mtr0log.h:.{1,30} void mtr_t::memcpy.{1,500}: Assertion .w == OPT. failed' ],

    # 2020-03-16 actual 10.5
    # mariabackup: /home/mleich/10.5/storage/innobase/page/page0cur.cc:2512: bool page_apply_insert_redundant(const buf_block_t&, bool, ulint, ulint, size_t, size_t, const void*, size_t): Assertion `page_simple_validate_old(block.frame)' failed.
    [ 'TBR-260'    , 'mariabackup: .{1,150}page0cur.cc:.{1,30} bool page_apply_insert_redundant.{1,500}: Assertion .page_simple_validate_old\(block.frame\). failed' ],
    # mariabackup: /home/mleich/10.5/storage/innobase/page/page0cur.cc:2068: void page_mem_free(const buf_block_t&, rec_t*, size_t, size_t): Assertion `garbage >= extra_savings' failed.
    [ 'TBR-261'    , 'mariabackup: .{1,150}page0cur.cc:.{1,30} void page_mem_free.{1,150}: Assertion .garbage >= extra_savings. failed.' ],
    # mariabackup: /home/mleich/10.5/storage/innobase/page/page0cur.cc:2046: void page_mem_free(const buf_block_t&, rec_t*, size_t, size_t): Assertion `page_get_n_recs(block.frame) < (n_heap & 0x7fff)' failed.
    [ 'TBR-262'    , 'mariabackup: .{1,150}page0cur.cc:.{1,30} void page_mem_free.{1,150}: Assertion .page_get_n_recs\(block.frame\) < \(n_heap & 0x7fff\). failed.' ],
    # 2020-03-16 actual 10.5 non debug build
    # Index for table 'test/t4' is corrupt; try to repair it
    [ 'TBR-263'    , 'Index for table .{1,150} is corrupt; try to repair it' ],
    # [ERROR] InnoDB: Corrupted page identifier at 2837320893; set innodb_force_recovery=1 to ignore the record.
    [ 'TBR-264'    , '\[ERROR\] InnoDB: Corrupted page identifier at .{1,50} set innodb_force_recovery=1 to ignore the record' ],
],

'blacklist_statuses' => [
    'STATUS_OK',
],

'blacklist_patterns' => [
    # [ <search_pattern> , <description like MDEV-nnnn> ]
    # ---------------------------------------------------
    # RQG runs showing this pattern end frequent with the status
    # STATUS_ENVIRONMENT_FAILURE(110). In case its a grammar maintained by hand than the
    # grammar is faulty and should be corrected.
    # But grammar simplification and also grammar masking run some automatic mangling of
    # grammars which could lead to the same effect because of non avoidable and harmless
    # reason. So we throw the remainings of such runs away and save by that resources.
    [ 'bad_grammar' , 'Possible endless loop in grammar.'                                         ],
    #
    # Grammars could have the unfortunate runtime property to cause some dramatic growth
    # of storage space consumption. This is especially valid in case of grammars generated
    # - during test simplification
    # - via grammar masking.
    # Example: All DROPs and DELETEs were shrinked away.
    #
    # The rqg_batch.pl ResourceControl will try to prevent negative consequences by stopping
    # selected RQG runs and freeing the resources. But in case the speed of the changes
    # exceeds the capabilities of ResourceControl or ResourceControl is disabled than
    # some typical outcome (observed before ResourceControl was implemented) is:
    # The DB server asserts, threads and/or periodic reporters exit with (hopefully)
    # STATUS_SERVER_CRASHED, the reporter Backtrace prints content of the server error log
    # and lets some debugger analyze the core file and than RQG exits with (again hopefully)
    # STATUS_SERVER_CRASHED.
    # Than in case of some "unsharp" setup of the whitelists (statuses == STATUS_ANY_ERROR,
    # patterns empty) that all gets valuated as replay.
    # But its either
    # - (most likely) a replay of some known "natural" effect which is not a defect
    # or
    # - (quite unlikely) the replay of a defect but the surviving data are not sufficient
    #   for analysis and we should better not waste time on that.
    # Conclusion:
    # Runs where we hit trouble with storage space are "unwanted".
    # Server error log pattern: ..... (Error 28 is OS: No space left on device)
    # [ERROR] InnoDB: preallocating 12582912 bytes for file ./test/#sql-1f36d_10.ibd failed with error 28
    # [ERROR] InnoDB: preallocating 65536 bytes for file ./test/FTS_0000000000000524_00000000000005f9_INDEX_5.ibd failed with error 28
    [ 'bad_environment_1' , '\[ERROR\] InnoDB: preallocating .{1,120} with error 28'              ],
    # Debugger output pattern:
    #    BFD: Warning: <core file> is truncated: expected core file size >= 959647744, found: 55398400.
    [ 'bad_environment_2' , '  is truncated: expected core file size '                            ],
    #
    #### Open bugs (TBR == to be reported or already in JIRA, MDEV == in JIRA)
    # Seen in 10.5 some time ago
    # mysqld: /work/10.5/storage/innobase/row/row0log.cc:2121: dberr_t row_log_table_apply_update(que_thr_t*, ulint, const mrec_t*, const offset_t*, mem_heap_t*, mem_heap_t*, row_merge_dup_t*, const dtuple_t*): Assertion `log->blobs' failed.
    [ 'TBR-34'     , 'mysqld: .{1,150}row0log.cc:.{1,30} dberr_t row_log_table_apply_update.{1,200}: Assertion .log->blobs. failed.' ],
    # 2020-03-03T19:53:31 [100471] | mysqld: /home/mleich/10.5/storage/innobase/row/row0log.cc:1183: dberr_t row_log_table_get_pk_col(const dict_field_t*, const dict_index_t*, dfield_t*, mem_heap_t*, const rec_t*, const offset_t*, ulint, ulint, ulint, const row_log_t*): Assertion `0' failed.
    [ 'TBR-221'    , 'mysqld: .{1,150}row0log.cc:.{1,20} dberr_t row_log_table_get_pk_col.{1,300}: Assertion .0. failed.' ],
    #
    #
    [ 'TBR-50'     , 'mysqld: .{1,150}rem0rec.cc:.{1,30} ulint rec_get_converted_size_comp_prefix_low.{1,300}: Assertion .field->col->is_dropped.. .. .field->col->mbmaxlen .. len >= field->col->mbminlen . fixed_len . field->col->mbmaxlen. failed.' ],
    [ 'TBR-51'     , 'mysqld: .{1,150}row0sel.cc:.{1,30} dberr_t row_search_mvcc.{1,150}: Assertion .0. failed.' ],
    # mysqld: /work/bb-10.5-MDEV-12353/storage/innobase/btr/btr0cur.cc:4139: void btr_cur_upd_rec_in_place(rec_t*, const dict_index_t*, const offset_t*, const upd_t*, buf_block_t*, mtr_t*): Assertion `!rec_offs_nth_sql_null(offsets, n)' failed.
    [ 'TBR-55'     , 'mysqld: .{1,150}btr0cur.cc:.{1,30} void btr_cur_upd_rec_in_place.{1,150}: Assertion .\!rec_offs_nth_sql_null\(offsets, n\). failed.' ],
    # Need Test
    [ 'TBR-56'     , 'mysqld:.{1,150}handler0alter.cc:.{1,30}: bool innobase_rename_or_enlarge_column_try.{1,150}: Assertion .\!\(\(col->prtype \^ prtype\) \& \~\(16384U\|32768U\)\). failed' ],
    #
    [ 'MDEV-17843' , 'mysqld: .{1,150}lock0lock.cc:.{1,30} bool lock_rec_queue_validate\(.{1,250}\): Assertion .page_rec_is_leaf\(rec\). failed.' ],
    # Fix is on move up
    [ 'MDEV-18911' , 'mysqld: .{1,150}row0sel.cc:.{1,30} void row_sel_field_store_in_mysql_format_func.{1,250}: Assertion .\(templ->is_virtual \&\& \!field\) \|\| \(field \&\& field->prefix_len \? field->prefix_len == len : templ->mysql_col_len == len\). failed.' ],
    [ 'MDEV-19130' , 'mysqld:.{1,150}handler.cc:.{1,30}: int handler::update_auto_increment\(\): Assertion .next_insert_id >= auto_inc_interval_for_cur_row.minimum\(\). failed' ],
    # Needs replay test
    [ 'MDEV-21325' , 'mysqld: .{1,150}trx0rec.cc:.{1,30} byte\* trx_undo_log_v_idx.{1,300}: Assertion .n_idx > 0. failed.' ],
    # 2020-02-05T20:29:25 [282821] #3  <signal handler called>
    # 2020-02-05T20:29:25 [282821] #4  0x00005653c2e1c3d0 in init_fts_doc_id_for_ref (table=table@entry=0x7fb06c074150, depth=depth@entry=0x7fb10cf28018) at /work/10.4/storage/innobase/row/row0mysql.cc:1774
    # 2020-02-05T20:29:25 [282821] #5  0x00005653c2e1f267 in init_fts_doc_id_for_ref (depth=0x7fb10cf28018, table=0x7fb06c074150) at /work/10.4/storage/innobase/row/row0mysql.cc:1757
    # 2020-02-05T20:29:25 [282821] #6  row_update_for_mysql
    [ 'TBR-200'    , '<signal handler called>.{1,500}init_fts_doc_id_for_ref.{1,500}init_fts_doc_id_for_ref.{1,500}row_update_for_mysql' ],
    [ 'TBR-201'    , 'InnoDB: Failing assertion: index_cache->words == NULL' ],
    # 2020-02-05T20:35:17 [264665] #3  <signal handler called>
    # 2020-02-05T20:35:17 [264665] #4  dict_col_t::detach (index=..., this=0x0) at /work/10.4/storage/innobase/include/dict0mem.h:1333
    # 2020-02-05T20:35:17 [264665] #5  dict_index_t::detach_columns (this=0x7fd9000d7670) at /work/10.4/storage/innobase/include/dict0mem.h:1192
    # 2020-02-05T20:35:17 [264665] #6  dict_mem_index_free
    [ 'TBR-202'    , '<signal handler called>.{1,500}dict_col_t::detach.{1,500}dict_index_t::detach_columns.{1,500}dict_mem_index_free' ],
    [ 'TBR-203'    , 'InnoDB: Failing assertion: strchr\(table->name.m_name, \'\/\'\) \!= NULL' ],
    # Looks like MDEV-21137 (has MTR tests) but that uses FOREIGN KEYs
    # mysqld: /work/10.4/storage/innobase/buf/buf0buf.cc:4840: buf_block_t* buf_page_get_gen(page_id_t, ulint, ulint, buf_block_t*, ulint, const char*, unsigned int, mtr_t*, dberr_t*): Assertion `mode == 16 || mode == 12 || !fix_block->page.file_page_was_freed' failed.
    [ 'TBR-204'    , 'mysqld: .{1,150}buf0buf.cc:.{1,30} buf_block_t\* buf_page_get_gen.{1,500}: Assertion .mode == 16 \|\| mode == 12 \|\| \!fix_block->page.file_page_was_freed. failed.' ],
    # mysqld: /work/10.4/storage/innobase/btr/btr0pcur.cc:157: void btr_pcur_store_position(btr_pcur_t*, mtr_t*): Assertion `page_get_page_no(block->frame) == index->page' failed.
    [ 'TBR-205'    , 'mysqld: .{1,150}btr0pcur.cc:.{1,30} void btr_pcur_store_position.{1,500}: Assertion .page_get_page_no\(block->frame\) == index->page. failed.' ],
    # 2020-02-07 bb-10.5-MDEV-12353
    # mysqld: /home/mleich/work/bb-10.5-MDEV-12353/storage/innobase/mtr/mtr0mtr.cc:619: ulint mtr_t::prepare_write(): Assertion `n_recs > 0' failed.
    [ 'TBR-206'    , 'mysqld: .{1,150}mtr0mtr.cc:.{1,30} ulint mtr_t::prepare_write\(\): Assertion .n_recs > 0. failed.' ],
    # 2020-02-07 bb-10.5-MDEV-12353
    # mysqld: /home/mleich/work/bb-10.5-MDEV-12353/storage/innobase/include/dyn0buf.h:311: ulint mtr_buf_t::size() const: Assertion `total_size == m_size' failed.
    [ 'TBR-207'    , 'mysqld: .{1,150}dyn0buf.h:.{1,30} ulint mtr_buf_t::size\(\) const: Assertion .total_size == m_size. failed.' ],
    # 2020-02-07 bb-10.5-MDEV-12353
    # mysqld: /home/mleich/work/bb-10.5-MDEV-12353/storage/innobase/include/dict0dict.ic:818: dict_field_t* dict_index_get_nth_field(const dict_index_t*, ulint): Assertion `index->magic_n == 76789786' failed.
    [ 'TBR-208'    , 'mysqld: .{1,150}dict0dict.ic:.{1,30} dict_field_t\* dict_index_get_nth_field.{1,500}: Assertion .index->magic_n == 76789786. failed.' ],
    # 2020-02-07 bb-10.5-MDEV-12353    but outside of InnoDB
    # # 2020-02-07T13:18:09 [139904] #3  <signal handler called>
    # 2020-02-07T13:18:09 [139904] #4  __memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:70
    # 2020-02-07T13:18:09 [139904] #5  0x00005570f1d06145 in native_compare (length=0x7fada03d8dd0, a=0x7fabc05ed888, b=0x7fabc05ed818) at /home/mleich/work/bb-10.5-MDEV-12353/mysys/ptr_cmp.c:49
    # 2020-02-07T13:18:09 [139904] #6  0x00005570f1cf1b63 in my_qsort2 (base_ptr=0x7fabc05ed818, count=15, size=8, cmp=0x5570f1d06111 <native_compare>, cmp_argument=0x7fada03d8dd0) at /home/mleich/work/bb-10.5-MDEV-12353/mysys/mf_qsort.c:154
    # 2020-02-07T13:18:09 [139904] #7  0x00005570f1620b5e in Filesort_buffer::sort_buffer
    [ 'TBR-209'    , '<signal handler called>.{1,500}__memcmp_sse4_1.{1,500}native_compare.{1,500}my_qsort2' ],
    # 2020-02-07 bb-10.5-MDEV-12353 after update
    # mysqld: /work/bb-10.5-MDEV-12353/storage/innobase/include/dict0dict.ic:817: dict_field_t* dict_index_get_nth_field(const dict_index_t*, ulint): Assertion `pos < index->n_def' failed.
    [ 'TBR-210'    , 'mysqld: .{1,150}dict0dict.ic:.{1,30} dict_field_t\* dict_index_get_nth_field.{1,500}: Assertion .pos < index->n_def. failed.' ],
    # 2020-02-07 bb-10.5-MDEV-12353 after update
    # mysqld: /work/bb-10.5-MDEV-12353/storage/innobase/rem/rem0rec.cc:1192: ulint rec_get_converted_size_comp_prefix_low(const dict_index_t*, const dfield_t*, ulint, ulint*, rec_comp_status_t, bool) [with bool mblob = false; ulint = long unsigned int]: Assertion `len <= field->col->len || ((field->col->mtype) == 5 || (field->col->mtype) == 14) || (field->col->len == 0 && field->col->mtype == 1)' failed.
    [ 'TBR-211'    , 'mysqld: .{1,150}rem0rec.cc:.{1,30} ulint rec_get_converted_size_comp_prefix_low.{1,500}: Assertion .len <= field->col->len \|\| \(\(field->col->mtype\) == 5 \|\| \(field->col->mtype\) == 14\) \|\| \(field->col->len == 0 \&\& field->col->mtype == 1\). failed.' ],
    # 2020-02-07 bb-10.5-MDEV-12353 after update
    # mysqld: /work/bb-10.5-MDEV-12353/storage/innobase/btr/btr0bulk.cc:113: dberr_t PageBulk::init(): Assertion `page_dir_get_n_heap(new_page) == 2U' failed.
    [ 'TBR-212'    , 'mysqld: .{1,150}btr0bulk.cc:.{1,30} dberr_t PageBulk::init\(\): Assertion .page_dir_get_n_heap\(new_page\) == 2U. failed.' ],
    # 2020-02-07 bb-10.5-MDEV-12353 after second update
    # mysqld: /work/bb-10.5-MDEV-12353/storage/innobase/page/page0cur.cc:1182: rec_t* page_cur_insert_rec_low(const page_cur_t*, dict_index_t*, const rec_t*, offset_t*, mtr_t*): Assertion `current_rec != insert_buf' failed.
    [ 'TBR-213'    , 'mysqld: .{1,150}page0cur.cc:.{1,30} rec_t\* page_cur_insert_rec_low.{1,500}: Assertion .current_rec \!= insert_buf. failed.' ],
    # 2020-02-07 bb-10.5-MDEV-12353 after second update   outside of InnoDB
    # mysqld: /work/bb-10.5-MDEV-12353/sql/sql_error.cc:335: void Diagnostics_area::set_ok_status(ulonglong, ulonglong, const char*): Assertion `!is_set() || (m_status == DA_OK_BULK && is_bulk_op())' failed.
    [ 'TBR-214'    , 'mysqld: .{1,150}sql_error.cc:.{1,30} void Diagnostics_area::set_ok_status.{1,500}: Assertion .\!is_set\(\) \|\| \(m_status == DA_OK_BULK \&\& is_bulk_op\(\)\). failed.' ],
    # seen in 10.5
    [ 'TBR-215'    , 'InnoDB: Index .{1,32} is marked as corrupted' ],
    # mysqld: /work/bb-10.5-MDEV-12353/storage/innobase/handler/handler0alter.cc:1448: bool instant_alter_column_possible(const dict_table_t&, const Alter_inplace_info*, const TABLE*, const TABLE*, bool): Assertion `!pk->has_virtual()' failed.
    [ 'TBR-216'    , 'mysqld: .{1,150}handler0alter.cc:.{1,20} bool instant_alter_column_possible.{1,300}: Assertion .\!pk->has_virtual\(\). failed.' ],
    # 10.5 2020-03-10
    # outside of innodb
    # # 2020-02-10T19:46:13 [251883] #3  <signal handler called>
    # 2020-02-10T19:46:13 [251883] #4  0x0000564aa3ca4135 in base_list_iterator::next_fast (this=0x7f7b4c15e1a0) at /work/bb-10.5-MDEV-12353/sql/sql_list.h:443
    # 2020-02-10T19:46:13 [251883] #5  0x0000564aa3dc8855 in List_iterator_fast<Item_equal>::operator++ (this=0x7f7b4c15e1a0) at /work/bb-10.5-MDEV-12353/sql/sql_list.h:620
    # 2020-02-10T19:46:13 [251883] #6  0x0000564aa3e5099e in substitute_for_best_equal_field
    [ 'TBR-217'    , '<signal handler called>.{1,500}base_list_iterator::next_fast.{1,500}List_iterator_fast.{1,500}substitute_for_best_equal_field' ],
    # 2020-02-11
    # mysqld: /work/bb-10.5-MDEV-12353/storage/innobase/page/page0cur.cc:1110: rec_t* page_cur_insert_rec_low(const page_cur_t*, dict_index_t*, const rec_t*, offset_t*, mtr_t*): Assertion `cur->rec != insert_buf' failed.
    [ 'TBR-218'    , 'mysqld: .{1,150}page0cur.cc:.{1,20} rec_t\* page_cur_insert_rec_low.{1,300}: Assertion .cur->rec \!= insert_buf. failed.' ],
    # # 2020-02-11T10:37:45 [310235] #3  <signal handler called>
    # 2020-02-11T10:37:45 [310235] #4  0x00005630ca7cc3c9 in buf_page_get_state (bpage=0x7fb654009f20) at /work/bb-10.5-MDEV-12353/storage/innobase/include/buf0buf.ic:220
    # 2020-02-11T10:37:45 [310235] #5  0x00005630ca7cc40e in buf_block_get_state (block=0x7fb654009f20) at /work/bb-10.5-MDEV-12353/storage/innobase/include/buf0buf.ic:249
    # 2020-02-11T10:37:45 [310235] #6  0x00005630ca7ecfd2 in btr_blob_free
    [ 'TBR-220'    , '<signal handler called>.{1,500}buf_page_get_state.{1,500}buf_block_get_state.{1,500}btr_blob_free' ],
    # 10.5 2020-03-10
    # mysqld: /home/matthias/Server/bb-10.5-MDEV-12353/storage/innobase/row/row0log.cc:2450: const mrec_t* row_log_table_apply_op(que_thr_t*, ulint, row_merge_dup_t*, dberr_t*, mem_heap_t*, mem_heap_t*, const mrec_t*, const mrec_t*, offset_t*): Assertion `0' failed.
    [ 'TBR-222'    , 'mysqld: .{1,150}row0log.cc:.{1,20} const mrec_t\* row_log_table_apply_op.{1,300}: Assertion .0. failed.' ],
    # mysqld: /home/matthias/Server/bb-10.5-MDEV-12353/storage/innobase/dict/dict0dict.cc:4536: void dict_table_check_for_dup_indexes(const dict_table_t*, check_name): Assertion `index1->is_committed() != index2->is_committed() || strcmp(index1->name, index2->name) != 0' failed.
    [ 'TBR-223'    , 'mysqld: .{1,150}dict0dict.cc:.{1,20} void dict_table_check_for_dup_indexes.{1,300}: Assertion .index1->is_committed\(\) \!= index2->is_committed\(\) \|\| strcmp\(index1->name, index2->name\) != 0. failed.' ],
    # InnoDB: Failing assertion: recv_recovery_is_on() || page_zip_validate( &bpage->zip, page, ((buf_block_t*) bpage)->index)
    [ 'TBR-224'    , 'InnoDB: Failing assertion: recv_recovery_is_on\(\) \|\| page_zip_validate\( \&bpage->zip, page, \(\(buf_block_t\*\) bpage\)->index\)' ],
    # InnoDB: Failing assertion: (block)->index || (block)->n_pointers == 0    # innodb_adaptive_hash_index problem
    [ 'MDEV-20203' , 'InnoDB: Failing assertion: \(block\)->index \|\| \(block\)->n_pointers == 0.' ],
    # Outside of InnoDB
    # 2020-02-14T17:34:57 [21095] #3  <signal handler called>
    # 2020-02-14T17:34:57 [21095] #4  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:303
    # 2020-02-14T17:34:57 [21095] #5  0x000055a8b042625a in my_copy_8bit (cs=0x55a8b10737a0 <my_charset_latin1>, dst=0x7f26141f9158 "", dst_length=8, src=0x8f00007f26142520 <error: Cannot access memory at address 0x8f00007f26142520>, src_length=8, nchars=8, status=0x7f2698151a30) at /home/mleich/Server/10.4/strings/ctype-simple.c:1169
    # 2020-02-14T17:34:57 [21095] #6  0x000055a8af81534f in String_copier::well_formed_copy (this=0x7f2698151a30, to_cs=0x55a8b10737a0 <my_charset_latin1>, to=0x7f26141f9158 "", to_length=8, from_cs=0x55a8b10737a0 <my_charset_latin1>, from=0x8f00007f26142520 <error: Cannot access memory at address 0x8f00007f26142520>, from_length=8, nchars=8) at /home/mleich/Server/10.4/sql/sql_string.cc:1079
    # 2020-02-14T17:34:57 [21095] #7  0x000055a8afa8a99f in Field_longstr::well_formed_copy_with_check (this=0x7f260c07fae0, to=0x7f26141f9158 "", to_length=8, from_cs=0x55a8b10737a0 <my_charset_latin1>, from=0x8f00007f26142520 <error: Cannot access memory at address 0x8f00007f26142520>, from_length=8, nchars=8, count_spaces=true, copy_length=0x7f2698151aa0) at /home/mleich/Server/10.4/sql/field.h:1916
    # 2020-02-14T17:34:57 [21095] #8  0x000055a8afa7d623 in Field_blob::store
    [ 'TBR-227'  , '<signal handler called>.{1,150}__memmove_avx_unaligned_erms.{1,800}my_copy_8bit.{1,800}String_copier::well_formed_copy' ],
    # SEGV
    # 2020-02-14T18:24:17 [30655] #3  <signal handler called>
    # 2020-02-14T18:24:17 [30655] #4  0x00005649959108b6 in dict_index_t::is_ibuf (this=0x0) at /home/mleich/Server/10.4/storage/innobase/include/dict0mem.h:1165
    # 2020-02-14T18:24:17 [30655] #5  0x0000564995b66a87 in btr_search_hash_table_validate (hash_table_id=2) at /home/mleich/Server/10.4/storage/innobase/btr/btr0sea.cc:2047
    # 2020-02-14T18:24:17 [30655] #6  0x0000564995b670da in btr_search_validate
    [ 'TBR-228'    , '<signal handler called>.{1,150}dict_index_t::is_ibuf.{1,800}btr_search_hash_table_validate.{1,800}btr_search_validate' ],
    # InnoDB: Failing assertion: addr.page == FIL_NULL || addr.boffset >= FIL_PAGE_DATA
    [ 'TBR-229'    , 'InnoDB: Failing assertion: addr.page == FIL_NULL \|\| addr.boffset >= FIL_PAGE_DATA' ],
    # 2020-02-14T19:45:16 [24149] #3  <signal handler called>
    # 2020-02-14T19:45:16 [24149] #4  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:303
    # 2020-02-14T19:45:16 [24149] #5  0x000055c681999dbd in mem_heap_dup (heap=0x7f2dcc066170, data=0x8f8f8f8f8f8f8f8f, len=9) at /home/mleich/Server/10.4/storage/innobase/include/mem0mem.h:242
    # 2020-02-14T19:45:16 [24149] #6  0x000055c681afebcb in dfield_dup (field=0x55c6858d3a50, heap=0x7f2dcc066170) at /home/mleich/Server/10.4/storage/innobase/include/data0data.ic:182
    # 2020-02-14T19:45:16 [24149] #7  0x000055c681b061fc in row_merge_buf_add
    [ 'TBR-230'    , '<signal handler called>.{1,150}__memmove_avx_unaligned_erms.{1,800}mem_heap_dup.{1,800}dfield_dup' ],
    # actual 10.5 but not InnoDB
    # 2020-02-18T13:42:41 [180191] #3  <signal handler called>
    # 2020-02-18T13:42:41 [180191] #4  0x00007f47f3d9f2a0 in __memmove_ssse3_back () from /lib64/libc.so.6
    # 2020-02-18T13:42:41 [180191] #5  0x000055711349893a in my_copy_8bit (cs=0x557114681da0 <my_charset_latin1>, dst=0x7f45440946b8 "", dst_length=499, src=0x6100007f45440601 <Address 0x6100007f45440601 out of bounds>, src_length=499, nchars=499, status=0x7f47f04b3dd0) at /home/matthias/Server/10.5/strings/ctype-simple.c:1169
    # 2020-02-18T13:42:41 [180191] #6  0x0000557112d63833 in charset_info_st::copy_fix (this=0x557114681da0 <my_charset_latin1>, dst=0x7f45440946b8 "", dst_length=499, src=0x6100007f45440601 <Address 0x6100007f45440601 out of bounds>, src_length=499, nchars=499, status=0x7f47f04b3dd0) at /home/matthias/Server/10.5/include/m_ctype.h:751
    # 2020-02-18T13:42:41 [180191] #7  0x0000557112d63152 in String_copier::well_formed_copy
    [ 'TBR-231'    , '<signal handler called>.{1,500}__memmove_ssse3_back.{1,500}my_copy_8bit.{1,500}charset_info_st::copy_fix' ],
    [ 'MDEV-16686' , 'mysqld: .{1,150}lock.cc:.{1,30} int lock_external\(THD\*, TABLE\*\*, uint\): Assertion .\(\*tables\)->reginfo.lock_type >= TL_READ. failed.' ],
    # closed
    # [ 'MDEV-17843' , 'mysqld: .{1,150}lock0lock.cc:.{1,30} bool lock_rec_queue_validate\(.{1,250}\): Assertion .page_rec_is_leaf\(rec\). failed.' ],
    # mysqld: /work/bb-10.5-MDEV-12353/storage/innobase/row/row0log.cc:3076: dberr_t row_log_table_apply_ops(que_thr_t*, row_merge_dup_t*, ut_stage_alter_t*): Assertion `0' failed.
    [ 'MDEV-18361' , 'mysqld: .{1,150}row0log.cc:.{1,20} dberr_t row_log_table_apply_ops.{1,300}: Assertion .0. failed.' ],
    [ 'MDEV-19555' , 'mysqld: .{1,150}sql_error.h:.{1,30} uint Diagnostics_area::sql_errno\(\) const: Assertion .m_status == DA_ERROR. failed.' ],
    [ 'MDEV-20038' , 'mysqld: .{1,150}btr0cur.cc:.{1,20} dberr_t btr_cur_search_to_nth_level_func.{1,300}: Assertion `rw_lock_own\(dict_index_get_lock\(index\), RW_LOCK_S\)\' failed.' ],
    [ 'MDEV-20618' , 'mysqld: .{1,150}row0upd.cc:.{1,30} dberr_t row_upd_sec_index_entry.{1,100}\): Assertion .btr_validate_index\(index, 0\). failed.' ],
    [ 'MDEV-21564-Rebirth' , 'mysqld: .{1,150}trx0purge.cc:.{1,30} void trx_purge_add_undo_to_history\(.{1,100}\): Assertion .srv_undo_sources \|\| trx->undo_no == 0 \|\| \(\!purge_sys.enabled\(\) .. \(srv_is_being_started \|\| trx_rollback_is_active \|\| srv_force_recovery >= SRV_FORCE_NO_BACKGROUND\)\) \|\| \(\(trx->mysql_thd \|\| trx->internal\) .. srv_fast_shutdown\). failed.' ],
    # mysqld: /work/10.5/storage/innobase/dict/dict0load.cc:1956: void dict_load_virtual_one_col(dict_table_t*, ulint, dict_v_col_t*, mem_heap_t*): Assertion `pos == vcol_pos' failed.
    [ 'MDEV-21663' , 'mysqld: .{1,150}dict0load.cc:.{1,30} void dict_load_virtual_one_col.{1,300}: Assertion .pos == vcol_pos. failed.' ],
    # mysqld: /home/matthias/Server/bb-10.5-MDEV-12353/storage/innobase/page/page0cur.cc:1306: rec_t* page_cur_insert_rec_low(const page_cur_t*, dict_index_t*, const rec_t*, offset_t*, mtr_t*): Assertion `rdm - rd + bd <= insert_buf + rec_size' failed.
    [ 'MDEV-21749' , 'mysqld: .{1,150}page0cur.cc:.{1,20} rec_t\* page_cur_insert_rec_low.{1,300}: Assertion .rdm - rd \+ bd <= insert_buf \+ rec_size.' ],
    # mysqld: /work/bb-10.5-MDEV-12353/storage/innobase/page/page0cur.cc:1312: rec_t* page_cur_insert_rec_low(const page_cur_t*, dict_index_t*, const rec_t*, offset_t*, mtr_t*): Assertion `!memcmp(insert_buf, rec - extra_size, rec_size)' failed.
    [ 'MDEV-21779' , 'mysqld: .{1,150}page0cur.cc:.{1,20} rec_t\* page_cur_insert_rec_low.{1,300}: Assertion .\!memcmp\(insert_buf, rec - extra_size, rec_size\). failed.' ],
    # mysqld: /work/10.5/storage/innobase/dict/dict0load.cc:1650: const char* dict_load_column_low(dict_table_t*, mem_heap_t*, dict_col_t*, table_id_t*, const char**, const rec_t*, ulint*): Assertion `vcol->v_pos == dict_get_v_col_pos(pos)' failed.
    [ 'MDEV-21800' , 'mysqld: .{1,150}dict0load.cc:.{1,30} const char\* dict_load_column_low.{1,300}: Assertion .vcol->v_pos == dict_get_v_col_pos\(pos\). failed.' ],
    # bb-10.5-MDEV-15528
    # mysqld: /home/mleich/bb-10.5-MDEV-15528/storage/innobase/buf/buf0flu.cc:371: void buf_flush_insert_into_flush_list(buf_block_t*, lsn_t): Assertion `(&log_sys.log_flush_order_mutex)->is_owned()' failed.
    [ 'TBR-15528_2' , 'mysqld: .{1,150}buf0flu.cc:.{1,30} void buf_flush_insert_into_flush_list.{1,300}: Assertion .\(\&log_sys.log_flush_order_mutex\)->is_owned\(\). failed.' ],
    # mysqld: /home/mleich/bb-10.5-MDEV-15528/storage/innobase/fil/fil0fil.cc:3952: dberr_t fil_io(const IORequest&, bool, page_id_t, ulint, ulint, ulint, void*, void*, bool): Assertion `len > 0' failed.
    [ 'TBR-15528_3' , 'mysqld: .{1,150}fil0fil.cc:.{1,30} dberr_t fil_io.{1,300}: Assertion .len > 0. failed.' ],
    # mysqld: /home/mleich/bb-10.5-MDEV-15528/storage/innobase/buf/buf0buf.cc:4934: buf_block_t* buf_page_create(page_id_t, ulint, mtr_t*): Assertion `buf_page_get_io_fix(&block->page) == BUF_IO_NONE' failed.
    [ 'TBR-15528_4' , 'mysqld: .{1,150}buf0buf.cc:.{1,30} buf_block_t\* buf_page_create.{1,300}: Assertion .buf_page_get_io_fix\(\&block->page\) == BUF_IO_NONE. failed.' ],
    # 10.5
    # SUMMARY: AddressSanitizer: use-after-poison /home/mleich/10.5/storage/innobase/page/page0cur.cc:1569 in page_cur_insert_rec_low(page_cur_t const*, dict_index_t*, unsigned char const*, unsigned short*, mtr_t*)
    [ 'MDEV-21850' , 'SUMMARY: AddressSanitizer: use-after-poison.{1,150}page0cur.cc:.{1,30} in page_cur_insert_rec_low\(page_cur_t const\*, dict_index_t\*, unsigned char const\*, unsigned short\*, mtr_t\*\)' ],
    # In review 2020-03-04
    # mysqld: /home/mleich/10.5/sql/ha_partition.cc:4405: virtual int ha_partition::update_row(const uchar*, const uchar*): Assertion `old_part_id == m_last_part' failed.
    [ 'MDEV-17091' , 'mysqld: .{1,150}ha_partition.cc:.{1,30} virtual int ha_partition::update_row.{1,300}: Assertion .old_part_id == m_last_part. failed.' ],
    # 10.5
    # mysqld: /home/mleich/Server/10.5/storage/innobase/lock/lock0lock.cc:6225: my_bool lock_table_locks_lookup(rw_trx_hash_element_t*, const dict_table_t*): Assertion `!dict_index_is_online_ddl(lock->index) || lock->index->is_primary()' failed.
    [ 'TBR-98' , 'mysqld: .{1,150}lock0lock.cc:.{1,30} my_bool lock_table_locks_lookup.{1,150}: Assertion .\!dict_index_is_online_ddl\(lock->index\) \|\| lock->index->is_primary\(\). failed.' ],
    # 10.4 2020-03-05
    # SEGV with virtual columns
    # 2020-03-05T11:49:36 [27071] #3  <signal handler called>
    # 2020-03-05T11:49:36 [27071] #4  0x0000564bd732b35b in ha_innobase::commit_inplace_alter_table (this=0x7f1bd0097e90, altered_table=0x7f1c644e9840, ha_alter_info=0x7f1c644e97b0, commit=true) at /home/mleich/10.4/storage/innobase/handler/handler0alter.cc:11208
    # 2020-03-05T11:49:36 [27071] #5  0x0000564bd7095918 in handler::ha_commit_inplace_alter_table (this=0x7f1bd0097e90, altered_table=0x7f1c644e9840, ha_alter_info=0x7f1c644e97b0, commit=true) at /home/mleich/10.4/sql/handler.cc:4568
    # 2020-03-05T11:49:36 [27071] #6  0x0000564bd6e15de6 in mysql_inplace_alter_table (thd=0x7f1bb8000ce8, table_list=0x7f1bb8011708, table=0x7f1bd00915e8, altered_table=0x7f1c644e9840, ha_alter_info=0x7f1c644e97b0, inplace_supported=HA_ALTER_INPLACE_INSTANT, target_mdl_request=0x7f1c644ea610, alter_ctx=0x7f1c644eb140) at /home/mleich/10.4/sql/sql_table.cc:7768
    # 2020-03-05T11:49:36 [27071] #7  0x0000564bd6e1c9f6 in mysql_alter_table
    [ 'TBR-232'    , '<signal handler called>.{1,200}in ha_innobase::commit_inplace_alter_table.{1,500}handler::ha_commit_inplace_alter_table.{1,500}in mysql_inplace_alter_table.{1,500}in mysql_alter_table' ],
    # 10.4 2020-03-05
    # 10.5 2020-03-10
    [ 'TBR-36'     , 'InnoDB: Index .{1,30} contains .{1,10} entries, should be .{1,10}.' ],
    # 10.4 2020-03-05 most probably sibling of MDEV-20203 but for CHECK TABLE
    # 2020-03-05T12:24:28 [45153] #3  <signal handler called>
    # 2020-03-05T12:24:28 [45153] #4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
    # 2020-03-05T12:24:28 [45153] #5  0x00007fa1d3d70801 in __GI_abort () at abort.c:79
    # 2020-03-05T12:24:28 [45153] #6  0x000055cb3da9c64c in ut_dbg_assertion_failed (expr=0x55cb3e31bafc "(block)->n_pointers == 0", file=0x55cb3e31b388 "/home/mleich/10.4/storage/innobase/btr/btr0sea.cc", line=1488) at /home/mleich/10.4/storage/innobase/ut/ut0dbg.cc:60
    # 2020-03-05T12:24:28 [45153] #7  0x000055cb3db02444 in btr_search_build_page_hash_index (index=0x7fa128074560, block=0x7fa1b006f080, ahi_latch=0x55cb41bdb550, n_fields=1, n_bytes=0, left_side=0) at /home/mleich/10.4/storage/innobase/btr/btr0sea.cc:1488
    # 2020-03-05T12:24:28 [45153] #8  0x000055cb3db02949 in btr_search_info_update_slow (info=0x7fa1200cb768, cursor=0x7fa1240de760) at /home/mleich/10.4/storage/innobase/btr/btr0sea.cc:1562
    # 2020-03-05T12:24:28 [45153] #9  0x000055cb3dacf652 in btr_search_info_update
    [ 'TBR-233'    , '<signal handler called>.{1,500}in ut_dbg_assertion_failed.{1,100}\(block\)->n_pointers == 0.{1,500}btr_search_build_page_hash_index.{1,500}in btr_search_info_update_slow.{1,500}btr_search_info_update' ],
    # 10.4 2020-03-05
    # 2020-03-05T12:41:40 [58521] | 2020-03-05 12:39:41 0x7f7fa1535700  InnoDB: Assertion failure in file /home/mleich/10.4/storage/innobase/row/row0ins.cc line 263
    # 2020-03-05T12:41:40 [58521] | InnoDB: Failing assertion: !cursor->index->is_committed()
    [ 'TBR-1'      , 'InnoDB: Failing assertion: \!cursor->index->is_committed\(\)' ],
    # since 10.2
    [ 'MENT-189'   , 'InnoDB: Failing assertion: opt_no_lock' ],
    # since 10.2
    [ 'MDEV-18200' , 'InnoDB: Failing assertion: success' ],
    # Older
    # mysqld: /home/mleich/10.5/storage/innobase/handler/handler0alter.cc:564: bool dict_table_t::instant_column(const dict_table_t&, const ulint*): Assertion `v.v_indexes.empty()' failed.
    [ 'TBR-234'    , 'mysqld: .{1,150}handler0alter.cc:.{1,30} bool dict_table_t::instant_column.{1,150}: Assertion .v.v_indexes.empty\(\). failed.' ],
    # 10.5 2020-03-10   looks similar to the closed https://jira.mariadb.org/browse/MDEV-14068
    # mysqld: /home/mleich/10.5/storage/innobase/row/row0sel.cc:3362: dberr_t Row_sel_get_clust_rec_for_mysql::operator()(row_prebuilt_t*, dict_index_t*, const rec_t*, que_thr_t*, const rec_t**, offset_t**, mem_heap_t**, dtuple_t**, mtr_t*): Assertion `0' failed.
    [ 'TBR-235'    , 'mysqld: .{1,150}row0sel.cc:.{1,30} dberr_t Row_sel_get_clust_rec_for_mysql::operator\(\).{1,500}: Assertion .0. failed.' ],
    # 10.5 2020-03-10
    # mysqld: /home/mleich/10.5/storage/innobase/log/log0log.cc:1407: bool log_checkpoint(): Assertion `oldest_lsn >= log_sys.last_checkpoint_lsn' failed.
    [ 'TBR-236'    , 'mysqld: .{1,150}log0log.cc:.{1,30} bool log_checkpoint\(\): Assertion .oldest_lsn >= log_sys.last_checkpoint_lsn. failed.' ],
    # 10.5 2020-03-10
    # mysqld: /home/mleich/10.5/storage/innobase/handler/ha_innodb.cc:12214: key_text::key_text(Key*): Assertion `(size_t)(ptr - buf) < MAX_TEXT - 4' failed.
    [ 'MDEV-21127' , 'mysqld: .{1,150}ha_innodb.cc:.{1,30} key_text::key_text.{1,30}: Assertion .\(size_t\)\(ptr - buf\) < MAX_TEXT - 4. failed.' ],
    # 10.1 2020-03-11 , has MTR test
    # mysqld: /home/mleich/bb-10.1-kevgs/sql/mdl.cc:2313: bool MDL_context::upgrade_shared_lock(MDL_ticket*, enum_mdl_type, double): Assertion `mdl_ticket->m_type == MDL_SHARED_UPGRADABLE || mdl_ticket->m_type == MDL_SHARED_NO_WRITE || mdl_ticket->m_type == MDL_SHARED_NO_READ_WRITE' failed.
    [ 'MDEV-18418' , 'mysqld: .{1,150}mdl.cc:.{1,30} bool MDL_context::upgrade_shared_lock.{1,500}: Assertion .mdl_ticket->m_type == MDL_SHARED_UPGRADABLE \|\| mdl_ticket->m_type == MDL_SHARED_NO_WRITE \|\| mdl_ticket->m_type == MDL_SHARED_NO_READ_WRITE. failed.' ],
    # 10.1 dev tree 2020-03-11    MTR Test is missing
    # InnoDB: Failing assertion: !((system_charset_info)->coll->strcasecmp((system_charset_info), (from), (s)))
    [ 'MDEV-20599' , 'InnoDB: Failing assertion: \!\(\(system_charset_info\)->coll->strcasecmp\(\(system_charset_info\), \(from\), \(s\)\)\)' ],
    # 10.1 dev tree 2020-03-11    MTR Test exists
    # mysqld: /home/mleich/bb-10.1-kevgs/storage/xtradb/handler/handler0alter.cc:2665: const char** innobase_get_col_names(Alter_inplace_info*, const TABLE*, const TABLE*, const dict_table_t*, mem_heap_t*): Assertion `user_table->n_def > table->s->fields' failed.
    [ 'MDEV-16500' , 'mysqld: .{1,150}handler0alter.cc:.{1,30} const char\*\* innobase_get_col_names.{1,300}: Assertion .user_table->n_def > table->s->fields. failed.' ],
    # 10.1 dev tree 2020-03-11    MTR Test exists
    # mysqld: /home/mleich/bb-10.1-kevgs/sql/sql_base.cc:2873: void Locked_tables_list::unlock_locked_tables(THD*): Assertion `thd->transaction.stmt.is_empty()' failed.
    [ 'MDEV-17749' , 'mysqld: .{1,150}sql_base.cc:.{1,30} void Locked_tables_list::unlock_locked_tables.{1,300}: Assertion .thd->transaction.stmt.is_empty\(\). failed.' ],
    # 10.1 dev tree 2020-03-11    MTR Test exists
    # mysqld: /home/mleich/bb-10.1-kevgs/sql/table_cache.cc:331: bool tc_release_table(TABLE*): Assertion `!table->pos_in_locked_tables' failed.
    [ 'MDEV-21680' , 'mysqld: .{1,150}table_cache.cc:.{1,30} bool tc_release_table.{1,30}: Assertion .\!table->pos_in_locked_tables. failed.' ],
    # 10.1 dev tree 2020-03-11    MTR Test exists
    # InnoDB: Failing assertion: pos < index->n_def
    [ 'MDEV-18047' , 'InnoDB: Failing assertion: pos < index->n_def' ],

    # 10.5 dev tree 2020-03-11
    # TBR-238 and TBR-240 could also occur in the same assert
    # mariabackup: /home/mleich/bb-10.5-MDEV-21907/storage/innobase/log/log0recv.cc:276: log_phys_t::apply_status log_phys_t::apply(const buf_block_t&, uint16_t&) const: Assertion `mach_read_from_4(frame + 4U) == block.page.id.page_no()' failed.
    [ 'TBR-238'    , 'mariabackup: .{1,150}log0recv.cc:.{1,30} log_phys_t::apply_status log_phys_t::apply.{1,100}: Assertion .mach_read_from_4\(frame \+ 4U\) == block.page.id.page_no\(\). failed.' ],
    # mariabackup: /home/mleich/bb-10.5-MDEV-21907/storage/innobase/page/page0cur.cc:2057: void page_mem_free(const buf_block_t&, rec_t*, size_t, size_t): Assertion `extra_savings < heap_top' failed.
    [ 'TBR-240'    , 'mariabackup: .{1,150}page0cur.cc:.{1,30} void page_mem_free.{1,100}: Assertion .extra_savings < heap_top. failed.' ],
    # mariabackup: /home/mleich/bb-10.5-MDEV-21907/storage/innobase/page/page0cur.cc:2926: bool page_apply_delete_dynamic(const buf_block_t&, ulint, size_t, size_t): Assertion `page_simple_validate_new(block.frame)' failed.
    [ 'TBR-239'    , 'mariabackup: .{1,150}page0cur.cc:.{1,30} bool page_apply_delete_dynamic.{1,100}: Assertion .page_simple_validate_new\(block.frame\). failed.' ],
    [ 'TBR-241'    , 'mariabackup: .{1,150}page0cur.cc:.{1,30} bool page_apply_insert_dynamic.{1,300}: Assertion .page_simple_validate_new\(block.frame\). failed.' ],

    # 10.5 dev tree 2020-03-12
    # mysqld: /home/mleich/bb-10.5-release/storage/innobase/buf/buf0lru.cc:622: void buf_flush_dirty_pages(ulint, bool, ulint): Assertion `first || buf_pool_get_dirty_pages_count(id) == 0' failed.
    [ 'MDEV-21843' , 'mysqld: .{1,150}buf0lru.cc:.{1,30} void buf_flush_dirty_pages.{1,50}: Assertion .first \|\| buf_pool_get_dirty_pages_count\(id\) == 0. failed.' ],
    # Outside of InnoDB
    # mysqld: /home/mleich/bb-10.5-release/sql/sql_base.cc:888: void close_thread_tables(THD*): Assertion `thd->transaction.stmt.is_empty() || thd->in_sub_stmt || (thd->state_flags & Open_tables_state::BACKUPS_AVAIL)' failed.
    [ 'MDEV-16929' , 'mysqld: .{1,150}sql_base.cc:.{1,30} void close_thread_tables.{1,50}: Assertion .thd->transaction.stmt.is_empty\(\) \|\| thd->in_sub_stmt \|\| \(thd->state_flags \& Open_tables_state::BACKUPS_AVAIL\). failed.' ],
    # mysqld: /home/mleich/bb-10.5-thiru/storage/innobase/include/dict0dict.ic:370: dict_col_t* dict_table_get_nth_col(const dict_table_t*, ulint): Assertion `pos < table->n_def' failed.
    # followed by ALTER        looks similar to https://jira.mariadb.org/browse/MDEV-19173 but here is no upgrade involved
    [ 'TBR-242'    , 'mysqld: .{1,150}dict0dict.ic:.{1,30} dict_col_t\* dict_table_get_nth_col.{1,300}: Assertion .pos < table->n_def. failed..{1,5000}Query.{1,50}: ALTER ' ],
    # Test exists but replays bad
    # mysqld: /home/mleich/bb-10.5-svoj/storage/innobase/row/row0purge.cc:484: bool row_purge_remove_sec_if_poss_leaf(purge_node_t*, dict_index_t*, const dtuple_t*): Assertion `0' failed.
    [ 'MDEV-20640' , 'mysqld: .{1,150}row0purge.cc:.{1,30} bool row_purge_remove_sec_if_poss_leaf.{1,150}: Assertion .0. failed.' ],

    # 10.5 dev tree 2020-03-12 with XA related stuff + --redefine=....xa.yy
    # 2020-03-13T10:56:11 [55619] #3  <signal handler called>
    # 2020-03-13T10:56:11 [55619] #4  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:371
    # 2020-03-13T10:56:11 [55619] #5  0x000055f2bcaa90f1 in dict_acquire_mdl_shared<false> (table=0x7fb1380ddde0, thd=0x55f2c1cdc8e8, mdl=0x55f2c1c7cbb8, table_op=DICT_TABLE_OP_NORMAL) at /home/mleich/bb-10.5-svoj/storage/innobase/dict/dict0dict.cc:902
    # 2020-03-13T10:56:11 [55619] #6  0x000055f2bca99d45 in dict_table_open_on_id (table_id=197, dict_locked=false, table_op=DICT_TABLE_OP_NORMAL, thd=0x55f2c1cdc8e8, mdl=0x55f2c1c7cbb8) at /home/mleich/bb-10.5-svoj/storage/innobase/dict/dict0dict.cc:944
    # 2020-03-13T10:56:11 [55619] #7  0x000055f2bc91a05f in row_purge_parse_undo_rec (node=0x55f2c1c7ca10, undo_rec=0x55f2c1c7e940 "", thr=0x55f2c1c7c958, updated_extern=0x7fb13e7fbb8e) at /home/mleich/bb-10.5-svoj/storage/innobase/row/row0purge.cc:933
    # 2020-03-13T10:56:11 [55619] #8  0x000055f2bc91a979 in row_purge
    [ 'TBR-250'    , '<signal handler called>.{1,100}__memmove_avx_unaligned_erms.{1,500}in dict_acquire_mdl_shared<false>.{1,500}in dict_table_open_on_id .{1,500}in row_purge_parse_undo_rec' ],
    [ 'TBR-251'    , 'InnoDB: Failing assertion: lock->index == index' ],
    # mysqld: /home/mleich/bb-10.5-svoj/storage/innobase/lock/lock0lock.cc:4815: bool lock_rec_queue_validate(bool, const buf_block_t*, const rec_t*, const dict_index_t*, const offset_t*): Assertion `!index || (index)->is_clust() || !dict_index_is_online_ddl(index)' failed.
    [ 'TBR-252'    , 'mysqld: .{1,150}lock0lock.cc:.{1,30} bool lock_rec_queue_validate.{1,500}: Assertion .\!index \|\| \(index\)->is_clust\(\) \|\| \!dict_index_is_online_ddl\(index\). failed' ],
    # SEGV Outside of InnoDB
    # Thread 1
    # 2020-03-16T12:35:57 [42967] #0  0x0000560077c7c2fe in Send_field::Send_field (this=0x7f5921799a70, thd=0x7f56fc000d08, item=0x8f8f8f8f8f8f8f8f) at /home/mleich/10.5/sql/field.cc:10753
    # 2020-03-16T12:35:57 [42967] #1  0x0000560077818a1a in Protocol_text::store_field_metadata (this=0x7f5921799b90, thd=0x7f56fc000d08, item=0x8f8f8f8f8f8f8f8f, pos=9) at /home/mleich/10.5/sql/protocol.cc:1040
    # 2020-03-16T12:35:57 [42967] #2  0x00005600778184a1 in Protocol::send_result_set_metadata (this=0x7f56fc0012d0, list=0x7f5921799c50, flags=3) at /home/mleich/10.5/sql/protocol.cc:958
    # 2020-03-16T12:35:57 [42967] #3  0x00005600779f485c in mysqld_list_processes (thd=0x7f56fc000d08, user=0x0, verbose=true) at /home/mleich/10.5/sql/sql_show.cc:2862
    # 2020-03-16T12:35:57 [42967] #4  0x000056007794d0e4 in mysql_execute_command (thd=0x7f56fc000d08) at /home/mleich/10.5/sql/sql_parse.cc:4897
    # 2020-03-16T12:35:57 [42967] #5  0x00005600779573aa in mysql_parse (thd=0x7f56fc000d08, rawbuf=0x7f56fc0119e0 "SHOW FULL PROCESSLIST
    # ........ (a lot unimportant stuff)
    # [ERROR] mysqld got signal 11 ;
    [ 'TBR-254'    , 'Thread 1 .{1,250} #0 .{1,30} in Send_field::Send_field .{1,500} at .{1,30}field.cc.{1,3000}SHOW FULL PROCESSLIST' ],

    # 2020-03-17 actual 10.3
    # InnoDB: Failing assertion: (block)->index || my_atomic_loadlint(&(block)->n_pointers) == 0
    [ 'MDEV-20824' , 'InnoDB: Failing assertion: \(block\)->index \|\| my_atomic_loadlint\(&\(block\)->n_pointers\) == 0' ],
    # 2020-03-17 actual 10.3
    # 2020-03-16T21:29:18 [31366] #3  <signal handler called>     Just a SEGV during CHECK TABLE EXTENDED
    # 2020-03-16T21:29:18 [31366] #4  0x00005624ecb18e94 in dict_index_is_ibuf (index=0x0) at /home/mleich/10.3/storage/innobase/include/dict0dict.ic:303
    # 2020-03-16T21:29:18 [31366] #5  0x00005624ecb221a3 in btr_search_hash_table_validate (hash_table_id=2) at /home/mleich/10.3/storage/innobase/btr/btr0sea.cc:2047
    # 2020-03-16T21:29:18 [31366] #6  0x00005624ecb227fc in btr_search_validate () at /home/mleich/10.3/storage/innobase/btr/btr0sea.cc:2145
    # 2020-03-16T21:29:18 [31366] #7  0x00005624ec847b4c in ha_innobase::check
    [ 'MDEV-K0001' , '<signal handler called>.{1,300} in dict_index_is_ibuf .{1,300} in btr_search_hash_table_validate .{1,300} in btr_search_validate .{1,300} in ha_innobase::check.{1,3000}CHECK TABLE' ],
    # 2020-03-17 actual 10.3
    # [ERROR] InnoDB: Record in index `uidx2` of table `test`.`t3` was not found on update: TUPLE (info_bits=0, 2 fields): {[4]    (0x80000004),[4]    (0x80000001)} at: COMPACT RECORD(info_bits=0, 2 fields): {[4]    (0x80000000),[4]    (0x80000001)}
    # 2020-03-16T22:18:23 [31566] | mysqld: /home/mleich/10.3/storage/innobase/row/row0upd.cc:2442: dberr_t row_upd_sec_index_entry(upd_node_t*, que_thr_t*): Assertion `btr_validate_index(index, 0, false)' failed.
    # I pick the first because it is a fatal error independend of if we get an assert or not
    [ 'MDEV-20763' , '\[ERROR\] InnoDB: Record in index .{1,40} of table .{1,100} was not found on update: ' ],

    # Open since long time
    [ 'MDEV-14865' , 'mysqld: .{1,100}ma_close.c:.{1,30} maria_close: Assertion .share->now_transactional == share->base.born_transactional. failed. ' ],

    # Seen on 10.2
    [ 'MDEV-18418' , 'mysqld: .{1,150}mdl.cc:.{1,30} bool MDL_context::upgrade_shared_lock.{1,150}: Assertion .mdl_ticket->m_type == MDL_SHARED_UPGRADABLE \|\| mdl_ticket->m_type == MDL_SHARED_NO_WRITE \|\| mdl_ticket->m_type == MDL_SHARED_NO_READ_WRITE \|\| mdl_ticket->m_type == MDL_SHARED_READ \|\| mdl_ticket->m_type == MDL_SHARED_WRITE. failed.' ],

    # [Warning] InnoDB: Using a partial-field key prefix in search, index `s` of table `test`.`table2_innodb_int_autoinc`. Last data field length 63985 bytes, key ptr now exceeds key end by 60910 bytes. Key value in the MySQL format:
    # 2020-03-20T13:56:29 [31896] |  len 3075; hex 0100 ... a lot stuff
    # 2020-03-20T13:56:29 [31896] | mysqld: /home/mleich/bb-10.2-thiru/storage/innobase/row/row0sel.cc:2738: void row_sel_convert_mysql_key_to_innobase(dtuple_t*, byte*, ulint, dict_index_t*, const byte*, ulint, trx_t*): Assertion `0' failed.
    [ 'MDEV-21245' , '\[Warning\] InnoDB: Using a partial-field key prefix in search.{1,20000}mysqld: .{1,150}row0sel.cc:.{1,30} void row_sel_convert_mysql_key_to_innobase.{1,150}: Assertion .0. failed.' ],
],

'search_var_size' => 30000000,

}



